name: blnk_flutter
description: "Blnk Flutter Task."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  fluttertoast: ^8.2.8
  flutter_bloc: ^8.1.6
  conditional_builder_null_safety: ^0.0.6
  camera: ^0.11.0+2
  crop_your_image: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.0
  google_sign_in: ^5.4.2
  dio: ^5.0.0
  file_picker: ^5.0.0
  http: ^0.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/credentials/


flutter_native_splash:
  image: "assets/images/logo.png"
  background_image: "assets/images/splash.png"
  branding: "assets/images/branding.png"
  branding_bottom_padding: 120